### PR TITLE
Updating all requirements and adding req check and update scripts.

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by waprin** [comment]
lgtm

**Comment by jonparrott** [comment]
No reservations at all? :P

**Comment by jonparrott** [comment]
Tests are actually passing, datastore seems to like throwing 503 randomly.

We should figure out how to mark tests as flaky.

**Comment by waprin** [comment]
Should I have reservations? I thought it looked like you copied the update pattern from python-docs-samples which makes sense to me. As I mentioned back then I think we should consider using nvie/pip-tools but your thing seems reasonable.

**Comment by jonparrott** [comment]
I was just messing with you. Pip-tools still doesn't do exactly what I want, but it may be worthwhile to fork it or establish something similar.

**Pull request merged**
