### PR TITLE
[don't merge] Various updates

### PR DESCRIPTION
**Pull request by jonparrott**
* Removing custom docker image and moving to new python runtime in testing. The docker image location is temporary.
* Less hacky entrpoint thanks to the new runtime activating virtualenv automatically.
* Removing resource and scaling configuration from app.yaml and worker.yaml.
* Removing unused env variables from app.yaml and worker.yaml
* Deleted oauth2 and switched to oauth2client's built-in flask_util.
* Added logout view to bookshelf/__init__.py
* Added authorization callback request_user_info to bookshelf/__init__.py to grab the user's google+ profile.
* Removed logging code and dropped down to just performing basic setup for the built-in loggin module.
* Upgraded gcloud to 0.7.1 and fixed storage.
* Significantly reduced the amount of code in main.py - it now just handles creating the app, exposing the queue, and running the app locally. Running the app live is handled by gunicorn in procfile.
* Removed the /_ah/stop handler from monitor, as it doesn't work as expected and interrupt signals are sent to the app anyways.

### CODE REVIEW

**Comment by waprin** [comment]
Code looks great. Only small issue I've seen is that it seems test_crud.testListByUser has broken because the way you fake the oauth2 credentials doesn't work anymore.

**Comment by jonparrott** [comment]
@waprin test fixed and a temporary full dockerfile has been added while we wait for the new python runtime. Do you think this looks good to merge and apply across branches?

**Comment by waprin** [comment]
Yep LGTM

**Comment by jonparrott** [comment]
I now have to figure out how to appropriately apply this to ... every branch. :(

**Comment by waprin** [comment]
If you want to divide the branches I can do half of them.

**Comment by jonparrott** [comment]
Let me think on it. None of these updates are critical yet.

**Comment by jonparrott** [comment]
I'm going to rewrite the history on this repository and push all new branches. I feel this is the best way to handle an update this big.

**Pull request closed without merging**
