### PR TITLE
Has the servers listen on 0.0.0.0

### PR DESCRIPTION
**Pull request by wilford**
Has the servers listen on 0.0.0.0. This makes it so that it works smoother inside the Cloud Shell.

### CODE REVIEW

**Comment by jonparrott** [comment]
A question before I merge this:

Is is possible for cloud shell to just run a nginx proxy to handle all of this?

**Comment by wilford** [comment]
Hm, that's a great question. Currently the Cloud Shell runs on a Micro VM,
which is quite under powered so we don't want to run too many background
processes.  However, there might be some ip configuration we can update.

Let me investigate more and get back to you :)

**Comment by jonparrott** [comment]
Okay, I'll hold off on merging this until then.

**Comment by wilford** [comment]
Alright, thanks for the great idea, we're going to go with it!  I'll delete
this pull request.

**Comment by jonparrott** [comment]
Sweet. :) Glad I could help.

**Pull request closed without merging**
