### PR TITLE
Making yaml files templates, updating readme and makefile.

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by waprin** [comment]
Hmm I had actually done it this way for Django then changed it to one file. I think it's simpler to just have one file, the typical user changes it once on their end and then they're done. With the template files ehre I like how your `git status` is clean, but the end-user still has to change config.py anyway. It's kind of bikeshedding a trivial issue, if you want it this way go ahead and merge, I still lean against it and I'm curious your expanded thoughts on it.

**Comment by jonparrott** [comment]
I can leave it as one file, that's fine. I agree we should be consistent - we should have `config.tmpl.py` if we're going to do this.  Will update.

**Comment by jonparrott** [comment]
Updated, take another look when you get a chance.

**Comment by waprin** [comment]
lgtm

**Pull request merged**
