### PR TITLE
chore: add common directories to dockerignore

### PR DESCRIPTION
**Pull request by markbrockettrobson**

### CODE REVIEW

**Comment by markbrockettrobson** [comment]
@googlebot I signed it!

**Comment by dandhlee** [comment]
Thanks for filing this PR @markbrockettrobson ! Could you help explain why we should be adding those directories to the docker ignore? Are there any tests failing, or does it interfere with your work in the container?

**Comment by dandhlee** [comment]
@markbrockettrobson friendly ping :)

**Comment by markbrockettrobson** [comment]
No tests are failing.
As a sample project, I believe that you intend to have people use this as a base for their projects. 
When building containers docker needs to index all files in the build context and this can take a fair amount of time. 
Adding Some files to the docker ignore can speed this up somewhat and the 3 I have added are fairly common for python projects.

**Review by dandhlee — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
